### ISSUE TITLE
Netbeans and latest Rsyn version

### ISSUE THREAD

**Issue by dmangira** [RsynTeam/rsyn-x#4]
At the latest version of the Rsyn there isn't any "/rsyn/x/ide/netbeans" path (as you explain here https://github.com/rsyn/rsyn-x/wiki/Using-NetBeans-IDE) in order to import the project to Netbeans. 

How can I import the Rsyn project into the Netbeans?
Also, it would be useful to update the "Running Timing Driven Placement Flow" section based on the latest version of the code. :)

Thanks

**Comment by gaflach** [comment]
Hi, Dimitris.

We'll take care of this layer today...

You may refer to rsyn-x/ispd18 to find a working NetBeans project that used
CMake.

We are making several changes to improve routing support, started using
CMake and switched from wxWidgets to Qt.
So it's a little bit messy, but we are cleaning things up.
Thanks for letting us know about the outdated information.

Regards,
Guilherme Flach

Still learning how to manage an open-source project

On Jan 24, 2018 08:54, "dimitris18" <notifications@github.com> wrote:

At the latest version of the Rsyn there isn't any "/rsyn/x/ide/netbeans"
path (as you explain here https://github.com/rsyn/rsyn-x
/wiki/Using-NetBeans-IDE) in order to import the project to Netbeans.

How can I import the Rsyn project into the Netbeans?
Also, it would be useful to update the "Running Timing Driven Placement
Flow" section based on the latest version of the code. :)

Thanks

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/rsyn/rsyn-x/issues/4>, or mute the thread

**Comment by gaflach** [comment]
I think the NetBeans project (/rsyn-x/x/ide/netbeans) is working fine now. 
The tutorials were also updated.

We are still working on the transition from wxWidgets to Qt, so a few things still need to be done to match all the functionality of the old interface.
