### ISSUE TITLE
run rsyn script in terminal

### ISSUE THREAD

**Issue by cgkantidis** [RsynTeam/rsyn-x#5]
Since the change to CMake, there is no /bin directory under /rsyn-x/x/. There is just the executable rsyn under /rsyn-x/build/bin/. How can I run a script with this executable? And also could you update the tutorials in the Wiki to reflect those changes?

**Comment by cgkantidis** [comment]
Actually I found it was `./rsyn --no-gui --script <name-of-script>.rsyn`. It would be nice if there was a `--help` option that would list the available options instead of inferring them from the source code. And also if there was the appropriate way specified in the Wiki.

**Comment by gaflach** [comment]
Hi, Christos.

We'll add the help option soon.
Thanks for the feedback.

Regards,
Guilherme Flach

On Mar 4, 2018 10:14, "Christos Gantidis" <notifications@github.com> wrote:

Actually I found it was ./rsyn --no-gui --script <name-of-script>.rsyn. It
would be nice if there was a --help option that would list the available
options instead of inferring them from the source code. And also if there
was the appropriate way specified in the Wiki.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/rsyn/rsyn-x/issues/5#issuecomment-370228628>, or mute
the thread
